### ISSUE TITLE
Update board page

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/innersourcecommons.org#107]
The ISC voted in a new board. The Board page here needs to be updated: https://innersourcecommons.org/about/board/

Details for the new board are here: https://docs.google.com/document/d/1VEJxuDIG_m4-eS3BRdJKn59NkadcvMx5r_AgxMB3k08/edit?usp=sharing

**Comment by clcoffey** [comment]
I'll pick this up.
