### ISSUE TITLE
Access to Assignees

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/innersourcecommons.org#108]
Can I please have access to assign myself to issues when I work on them?

Also, I have tried to move my cards into the Done section in Projects however I can't do it, even though the issues have been closed. Is this an automation problem or do I need specific access in order to do that too?

Any help would be much appreciated.

**Comment by voborgus** [comment]
Of course! Can you check it now please?

**Comment by clcoffey** [comment]
Sorry Dmitrii, it's still not working for me. (either of the above) :-(

**Comment by voborgus** [comment]
You should accept an invitation to the repository :) 

![image](https://user-images.githubusercontent.com/9394918/113694975-0a4fbe80-96d9-11eb-9e97-100a056e07a2.png)

**Comment by clcoffey** [comment]
Dmirtrii, you are a star! Thank you so much!
