### ISSUE TITLE
Are the bylaws outdated?

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/innersourcecommons.org#113]
**Describe the bug**

I noticed that the [bylaws on the website](https://innersourcecommons.org/documents/bylaws.pdf) are different from the [bylaws in gDrive](https://docs.google.com/document/d/109XWFL_MypH9V2gMd8my0YFzxOQkwJTF/edit). Is the one on the website potentially outdated?

**Expected behavior**

The most up-to-date version of the Foundation's bylaws should be published on the website.

**Comment by claredillon** [comment]
@MaineC - can you confirm that the bylaws in the gDrive document are the correct ones - or is there a version in GitHub we should take as the official version? Thanks!

**Comment by voborgus** [comment]
@MaineC up this thread

**Comment by MaineC** [comment]
https://drive.google.com/drive/u/0/folders/1njc78ay6tKdfoMmqqWWqz5-FwnBC9q-k ... this folder should hold the final version of the official docs. I can't figure out from which folder the doc was taken that is linked to by @spier 
...

**Comment by claredillon** [comment]
We have confirmed that the Bylaws on the website are indeed out of date. The version on the website is likely to be an artifact from the previous website that was copied over (dating from Dec 2017). I am checking with the board to get the latest ratified version so we can update.

**Comment by claredillon** [comment]
The latest bylaws have been uploaded in this PR: https://github.com/InnerSourceCommons/innersourcecommons.org/pull/259. This was confirmed by the ISC board.
