### ISSUE TITLE
Learning Path video updated

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/innersourcecommons.org#132]
**Describe the bug**
We have updated the Learning Path Become an InnerSource Contributor Video on Youtube. This has broken the link on the website: https://innersourcecommons.org/learn/learning-path/contributor/02/ 

**Expected behavior**

The new video link is: https://youtu.be/S0Gps2AbZ7M 
Please update the link on the website so that the new video will be embedded and will play in the page.

**Additional context**
This issue is related to the Learning Path issue [#122](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/122)

**Comment by clcoffey** [comment]
@tsadler1988 and @voborgus is there any chance you could help with this?

**Comment by voborgus** [comment]
The easiest and the ugly way is to change the `youtubeCode` [directly](https://github.com/InnerSourceCommons/innersourcecommons.org/blob/master/content/learn/learning-path/contributor/02.md):
![image](https://user-images.githubusercontent.com/9394918/123831665-3b711100-d90d-11eb-9b8f-4dba00760a8b.png)

But much better to wait for @tsadler1988 for correct change with re-generation from learning path sources.

**Comment by tsadler1988** [comment]
For now there are quite a few manual steps:
1. Update the URL in the [config](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/config/urls.yaml)
1. Open a PR on https://github.com/InnerSourceCommons/InnerSourceLearningPath
1. Get the PR merged
1. [Regenerate the Learning Path markdown](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/scripts#how-to-update-innersourcecommonsorg-with-new-articles)
1. Open a PR on https://github.com/InnerSourceCommons/innersourcecommons.org
1. Once PR is merged the website will update automatically

Steps 4 and 5 will be automated soon...if you're keen to get this out quickly then maybe update directly for now as @voborgus said, although **please do steps 1-3 above to avoid the URL reverting to the old video**.

**Comment by clcoffey** [comment]
Thanks @tsadler1988 and @voborgus 
I've done steps 1 & 2 in Tom's list. 
Waiting for step 3

**Comment by clcoffey** [comment]
I have done steps 1-3 above. 
When doing step 4 and running "npm ci" I get an error: 
<b> no such file or directory, open '/Users/cristinacoffey/Documents/GitHub/InnerSourceLearningPath/package.json'</b>

Any idea how I can fix this? Alternatively, I can just wait for the automation.

**Comment by clcoffey** [comment]
Ok, it took me a while but I managed to get through all the steps :-)

**Comment by tsadler1988** [comment]
I think there's 1 missing step on the YouTube side - the new video doesn't seem to have a proper thumbnail (https://img.youtube.com/vi/v3aRZkbTSmY/mqdefault.jpg). Not sure how to do this I'm afraid, but these are used on the website so could do with being updated.

I'm not sure if we have copies of the thumbnails anywhere, but re-using the old video's thumbnail should be fine.

**Comment by voborgus** [comment]
@tsadler1988 seems the URL for thumbnail in this PR is correct and working and we can merge this: 
https://img.youtube.com/vi/S0Gps2AbZ7M/mqdefault.jpg

**Comment by tsadler1988** [comment]
Ohh I was looking at the old video ID - my mistake!
