### ISSUE TITLE
InnerSource in Action Page 

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/innersourcecommons.org#231]
Bring in from https://github.com/InnerSourceCommons/innersourcecommons.org/pull/230

@spier noticed:

- The citation text for Walmart and WayFair is the same (likely a bug)
- The citation fo GitHub sounds strange to me:
"The reason why InnerSource works is because like open source you're working with people who are collaborating with different priorities kind of thing because they're working on different things".
From "kind of thing ..." onwards I don't understand what it means anymore

**Comment by clcoffey** [comment]
@Katiegilroyy can you check these?

**Comment by spier** [comment]
Excellent. Thanks!

**Comment by clcoffey** [comment]
I added these tasks to a new issue in the Marketing Repository https://github.com/InnerSourceCommons/InnerSourceMarketing/issues/149 I will close it here.
