### ISSUE TITLE
One place to update the # of individuals in ISC

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/innersourcecommons.org#236]
**Is your feature request related to a problem? Please describe.**
As the number of individuals in ISC is continually growing, every time we update the website we have to change this number in multiple places. This is prone to introduce human error as some pages might be forgotten.

**Describe the solution you'd like**
Is there a way to include a constant that is used in all these places and just update the value of this constant rather than having to update all the different pages?

**Comment by clcoffey** [comment]
@spier and @voborgus any idea if this is possible?

**Comment by spier** [comment]
In how many places do we mention that number?
As an aside: Might be worth considering to reduce the number of places but that wasn't your question. 

I would suspect that Hugo has some **global context**. Maybe called **global variables** or similar. That could be used for this. 

Unfortunately I don't have time to look this up right now.

**Comment by clcoffey** [comment]
We mention it in 6 places. It's no rush, I can try and look it up as well. I just thought you might know how to do it off the top of your head :-) 

Thanks for taking the time to consider it.

**Comment by spier** [comment]
Looks like we could use a site param. We would define it in `config.yaml`. 


https://gohugo.io/variables/site/#the-siteparams-variable

**Comment by voborgus** [comment]
Done in #250
