### ISSUE TITLE
Translate to pt-BR

### ISSUE THREAD

**Issue by guiofsaints** [InnerSourceCommons/innersourcecommons.org#237]
Hello, I would like to start some translations of the Inner Source Common into Portuguese (pt-BR), where do I start?

Could anyone give me some recommendations of which project or file?

Tks

**Comment by lenucksi** [comment]
Hi @gui-text Depending on the content it would be a good way to reach out to the various trusted committers of the working group whose content you'd want to translate: @lenucksi or @rrrutledge or @tsadler1988 for the learning path content and patterns and @spier for more patterns stuff. I'm note sure who currently cares most for the general website parts but @voborgus might be a good first contact.

Hope that helps.

**Comment by rrrutledge** [comment]
If you want to translate the [learning path](https://innersourcecommons.org/learn/learning-path/) content.  Then you can check out our [README](https://github.com/InnerSourceCommons/InnerSourceLearningPath#readme) and [translation](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/CONTRIBUTING.md#translations) instructions.  We have an active community around the learning path and would love to support your translation efforts!

**Comment by guiofsaints** [comment]
I'll start with these links.

Thanks @rrrutledge @lenucksi

**Comment by rrrutledge** [comment]
Great!  You can find links to our Slack channel in the website if you want to join and chat more in there!
