### ISSUE TITLE
Set Up Google Analytics 4

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/innersourcecommons.org#261]
**Is your feature request related to a problem? Please describe.**
Google Analytics 4 is replacing Universal Analytics

> create a new Google Analytics 4 property and ensure that your setup is complete. If you haven't started collecting data in your Google Analytics 4 property, you should do so now. This will allow you to gather the historical insights you need to measure your results over time when Universal Analytics stops processing hits.

https://analytics.google.com/analytics/web/?utm_campaign=2022-q1-gbl-all-gafree&utm_source=google-growth&utm_medium=email&utm_content=ga-sunset-msa-ua-only-admin#/a186978221w261326046p236925889/admin/ga4-setup-assistant

**Comment by clcoffey** [comment]
Hi @voborgus I finally got the chance to look into this and I realise I don't have admin access to the google analytics site. If you get the chance could you look into switching us over?

**Comment by andrea-kyurchiev** [comment]
Closing this as it is resolved
