### ISSUE TITLE
Promote the new Services Directory instead of the State of InnerSource Suvey in the notice bar on website

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/innersourcecommons.org#292]
Propose replacing the notice on our website that currently says "The State of InnerSource 2021 is out! [Click here to Download and Read the research report!](https://innersourcecommons.org/learn/research/state-of-innersource-survey-2021/)" to "We have launched a new InnerSource Services Directory. Click here to check it out"
and a link to: https://innersourcecommons.org/community/services/

**Comment by clcoffey** [comment]
I just made the change in this Pull Request: https://github.com/InnerSourceCommons/innersourcecommons.org/pull/293
