### ISSUE TITLE
Add Microsoft Case Study to the site

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/innersourcecommons.org#330]
**Is your feature request related to a problem? Please describe.**
We have a new case study for Microsoft we wish to publish on the site. This is the first of what will be more case studies. The case study can be found [here](https://docs.google.com/document/d/1rR2zoXuZ6N5I808T3px6bCaOVPIFSUgI/edit?usp=sharing&ouid=111601782014637907784&rtpof=true&sd=true) 

**Describe the solution you'd like**

It's not determined yet how we will present multiple case studies. As a starting point propose:
- a page is created at https://innersourcecommons.org/community/casestudies/microsoft.md with the case study text.
- Linked / announced on the dark green banner on the home page (replacing the current announcement about the services directory). 

**Additional context**
Once that is done propose we discuss whether/how to create a case study page or include on the InnerSource in Action page or both.

**Comment by claredillon** [comment]
I note GitHub uses the term customer-stories rather than case studies... like that better. So perhaps we should have it at https://innersourcecommons.org/community/stories/microsoft.md 

It also makes me think about whether we should change the InnerSource in Action page to be InnerSource Stories? We've heard reports that people are not clear about finding evidence on "InnerSource in Action". Maybe we can discuss that later.

**Comment by voborgus** [comment]
Done in #331
