### ISSUE TITLE
Images not showing up in carousel on About page.

### ISSUE THREAD

**Issue by clcoffey** [InnerSourceCommons/innersourcecommons.org#369]
**Describe the bug**
Some images in the carousel on the About page are not showing up. 

**Expected behavior**
I expect to see all the images in the carousel
<img width="1084" alt="Screenshot 2022-09-20 at 12 17 02" src="https://user-images.githubusercontent.com/78749459/192518413-86d188f7-42df-4291-bb93-14f4feed408b.png">

**Comment by clcoffey** [comment]
Hi @voborgus, I am not sure if you have any time these days but I think you were the one that created this carousel. Any idea why the images don't show up?

**Comment by voborgus** [comment]
@clcoffey sure, a small fix in the PR above :)
