### ISSUE TITLE
Create a variable for the Slack Invite Link

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/innersourcecommons.org#454]
**Is your feature request related to a problem? Please describe.**
There are numerous places on the website that features a hardwired link to Slack invite. This has to be updated every now and again - it would really help to have one variable we update. 

**Describe the solution you'd like**
I am hoping a variable can be created that links to the following Slack invite link:
content/en/redirects/slack.md

This was created on the 9th Jan 2023 to never expire. Only 400 people can use the link and then I think it needs to be replaced. 

**Additional context**
Here are the places I have found that have the Slack link hard-coded:
- _index.md
- content/en/about/contact.md
- content/en/community/_index.md
- The Slack button redirect is here: content/en/redirects/slack.md

There may be more....

There were also a number of past event pages that had links to the old (expired) Slack link - I have not updated them, as I doubt folks will  be using those old pages to join Slack. 

Note I am not sure how this impacts the JP site. Does it have to be changed there too?

**Comment by spier** [comment]
Could we replace all occurrences of `https://join.slack.com/t/innersourcecommons/shared_invite/...` on our website with `https://innersourcecommons.org/slack`?

`https://innersourcecommons.org/slack` itself is a redirect that we can change whenever we need to (as you just did [here](https://github.com/InnerSourceCommons/innersourcecommons.org/pull/453/files)).

So I don't think that we need any hugo variable, as long as we always use `https://innersourcecommons.org/slack` when we want to point to our slack inviter.

**Comment by yuhattor** [comment]
I agree with Sebastian. I don't think it is necessary to set up a variable:)

**Comment by yuhattor** [comment]
Please take a look at #457  PR comment:)

**Comment by claredillon** [comment]
Ah - that's a perfect solution - thank you @spier and @yuhattor
