### ISSUE TITLE
New Members Announcement

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/innersourcecommons.org#559]
Hi @direnakkoc 

Please can you add a new announcement to our Announcements page: https://innersourcecommons.org/about/announcements/

Image and text are attached.

The announcement should follow the same format as previous announcements.

Thanks a million

[2023 June Members Announcement.docx](https://github.com/InnerSourceCommons/innersourcecommons.org/files/11668546/2023.June.Members.Announcement.docx)
![Members 2023](https://github.com/InnerSourceCommons/innersourcecommons.org/assets/101422261/77bf6be0-e0bd-4e90-b7cb-c6e0f5bdac91)

**Comment by CiaraFlanagan** [comment]
@claredillon 

Waiting for your go ahead re: finalization of text and quote.

**Comment by claredillon** [comment]
Here is the text - with jsut a couple of words updated. Quotes have been signed off by Daniel and Isabel.

June, 2022

We are delighted to announce the election of our new InnerSource Commons (ISC) Foundation [Members](https://innersourcecommons.org/about/members/): Guilherme Dellagustin, Yuki Hattori, Bill Higgins and Katie Schueths.

The InnerSource Commons community is open to all. However, some community participants go above and beyond, and may be invited to become ISC Foundation Members. As the InnerSource Commons is a membership corporation, ISC Members own and run the Foundation, serving a similar role to shareholders in publicly traded corporations.

“We are delighted to welcome our newest InnerSource Commons Foundation Members. Guilherme, Yuki, Bill, and Katie have all made significant contributions to the InnerSource Commons and we truly appreciate their dedication and support.” said Daniel Izquierdo-Cortázar, President of InnerSource Commons. 

The ISC Foundation follows the practice of the Apache Software Foundation. ISC Members nominate key contributors to InnerSource Commons and vote in new Members on an annual basis. Membership is purely merit-based, and restricted to individuals. 

“Our Members are crucial stakeholders within InnerSource Commons. It is fantastic to see more Members join us every year,” said Isabel Drost-Fromm, Chair of InnerSource Commons.

The full list of InnerSource Commons Members can be found on our [Members](https://innersourcecommons.org/about/members/) page. 

**About InnerSource Commons**

InnerSource Commons is the world’s largest community of InnerSource practitioners. It is dedicated to creating and sharing knowledge about InnerSource, the use of open source best practices for software development within the confines of an organization.

Founded in 2015, the InnerSource Commons supports and connects over 2000 individuals from over 750 companies, academic institutions, and government agencies. The InnerSource Commons Foundation was incorporated on February 19th, 2020 and is a 501(c)(3) public charity.

**Contact Information**

If you would like to learn more about InnerSource Commons or our Sponsor Program, please visit [Our Sponsors](https://innersourcecommons.org/about/sponsors/) page or contact us at: info@innersourcecommons.org.

June 7, 2023 (Insert the date that you create the pull request)

**Comment by CiaraFlanagan** [comment]
Thanks @direnakkoc and @andrea-kyurchiev
