### ISSUE TITLE
Fix twitter feed on home page

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/innersourcecommons.org#587]
Hi @andrea-kyurchiev 

The twitter feed on our home page is no longer working.  Can you take a look at this please?

**Comment by andrea-kyurchiev** [comment]
@CiaraFlanagan turns out it's an issue on Twitter's side as they have closed off the site for unregistered users and have broken the option to embed a feed in the meantime. Closing for now, would reopen if anything changes.
