### ISSUE TITLE
New announcement for announcements page

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/innersourcecommons.org#593]
Hi there @andrea-kyurchiev 

As discussed, I attach the image and text for the new announcement.

1. Can you double check that the current announcement is then moved the section where we have the previous announcements (I think you mentioned a bug about it disappearing the last time we posted a new announcement).

2. When you create the PR, please can you assign it to @rrrutledge, @dicortazar and myself.

Thanks very much!

[2023-08-03 Announcement.docx](https://github.com/InnerSourceCommons/innersourcecommons.org/files/12241208/2023-08-03.Announcement.docx)

![Russell ED](https://github.com/InnerSourceCommons/innersourcecommons.org/assets/101422261/0b7e0a8d-d9be-452d-b3a3-451d35bb0b41)

**Comment by andrea-kyurchiev** [comment]
That's it there @CiaraFlanagan I've made sure that only this announcement is featured so the previous one is correctly shown in the list below.
