### ISSUE TITLE
Make the site work on Mobile again

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/innersourcecommons.org#61]
**Is your feature request related to a problem? Please describe.**

If we can, we should try to get the website to work on Mobile as well.
While this doesn't come for free (it takes some work to get this done), the number of users on Mobile devices should make this worthwhile.

Also see screenshot.

![Screen Shot 2021-02-23 at 21 07 32 ](https://user-images.githubusercontent.com/163029/108901740-8acfc980-761b-11eb-8d0c-0431f29c515f.JPG)

**Comment by andrea-kyurchiev** [comment]
This seems to be resolved. The website looks fine on Android 13.  Maybe double check on your side @spier otherwise this could be closed.

**Comment by spier** [comment]
Just resolving this for now. If it comes up again, somebody will reopen it :)
