### ISSUE TITLE
"Join Mailing List" call to action not centered/overflowing background

### ISSUE THREAD

**Issue by andrea-kyurchiev** [InnerSourceCommons/innersourcecommons.org#610]
**Describe the bug**
The input overflows the background causing it to look like this:
![image](https://github.com/InnerSourceCommons/innersourcecommons.org/assets/77273562/c6dd7a59-3bac-47fe-8776-b921d35d3b93)
Tested on Brave browser. It looks a bit better in Chrome:
![image](https://github.com/InnerSourceCommons/innersourcecommons.org/assets/77273562/ef4f7181-3ccf-4df7-9e86-0396d0b3f43f)
but it's still off-centered

**Expected behavior**
The background will expand around the input and the input and label would be centered

**Comment by rrrutledge** [comment]
Looks good now.
