### ISSUE TITLE
Add 'State of InnerSource 2023' report to research section of website:

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/innersourcecommons.org#618]
The following image and content to be added to: https://innersourcecommons.org/learn/research/

![Slide background](https://github.com/InnerSourceCommons/innersourcecommons.org/assets/101422261/2583920a-d06b-4196-bee5-0b0b2726a581)

Heading: 'State of InnerSource Survey 2023'
Text underneath: Report of the 2022-2023 State of InnerSource Survey
Button:  'Read Research Report'

When clicking on the above button or heading, the reader should then come to a **new page**. The website link for for this page must be: https://innersourcecommons.org/learn/research/state-of-innersource-survey-2022-2023/

See format of https://innersourcecommons.org/learn/research/state-of-innersource-survey-2021/ for guide to formatting the page.

Heading/Title: State of InnerSource Survey 2022
Image: use the attached image
Button: 'Read Research Report' 

This button should link to the attached document 'State.of.InnerSource.Report.2022-2023.pdf'
[State.of.InnerSource.Report.2022-2023.pdf](https://github.com/InnerSourceCommons/innersourcecommons.org/files/12727312/State.of.InnerSource.Report.2022-2023.pdf)

See attached text for website page.
[Website Text.docx](https://github.com/InnerSourceCommons/innersourcecommons.org/files/12727612/Website.Text.docx)

**Comment by andrea-kyurchiev** [comment]
@CiaraFlanagan shouldn't the image match the title being 2022 instead of 2023?
