### ISSUE TITLE
Port book "Managing InnerSource Projects" into innersourcecommons.gitbook.io org

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/innersourcecommons.org#62]
**Is your feature request related to a problem? Please describe.**

**Note:** This is not strictly an issue of the website, but as the website will link to this book I am putting it here.

If we port the book "Managing InnerSource Projects" into the innersourcecommons.gitbook.io org, then we will have a more consistent association of the book with the ISC brand. I talked to Daniel about this already and he will confirm with Jose.

**Describe the solution you'd like**

Port:
- from: https://dicortazar.gitbook.io/managing-inner-source-projects/
- to: innersourcecommons.gitbook.io/managing-inner-source-projects/

While doing that we would likely have to move the respective GitHub repo into the ISC GitHub org as well.

**Comment by spier** [comment]
FYI @dicortazar

**Comment by dicortazar** [comment]
Thanks @spier , during today's meeting we agreed with having some kind of announcement and promote the book.
So we should take care this is ready to go before the ownership transfer.

**Comment by spier** [comment]
@dicortazar sounds good. 

To make this more actionable: What is the next step here and who has to take it?

**Comment by spier** [comment]
We have ported the book to https://innersourcecommons.gitbook.io/managing-inner-source-projects/, so I think there is nothing else to do on this issue.
