### ISSUE TITLE
Add an "InnerSource" definition right on the front page

### ISSUE THREAD

**Issue by vmbrasseur** [InnerSourceCommons/innersourcecommons.org#652]
**Describe the bug**

Howdy, team! I'm writing a sidebar about InnerSource for my [latest book](https://fossbiz.com). I want to be able to link readers to The One True Definition of InnerSource, so naturally I went to innersourcecommons.org.

Except the website has no obvious InnerSource definition _anywhere_. Imagine my surprise!

**Expected behavior**

I expected to visit innersourcecommons.org and find "InnerSource is [pithy definition]. InnerSource Commons is the world's largest community of InnerSource practitioners…".

**Additional context**

It's best not to assume that the people who show up the the site already know what InnerSource is. They may be there trying to learn that very thing, but currently they can't do so without a lot of clicking around and maybe even downloading the book. Make it easy for them: put the definition right there on the front page.

**Comment by dellagustin-sap** [comment]
Good call.
I like the definition that is currently used in Wikipedia: InnerSource is the use of open source software development best practices and the establishment of an open source-like culture within organizations 

I would leave out the second part: for the development of its non-open-source and/or proprietary software.

Reason: InnerSource is not restricted to Software, it is suitable for the production of other things and for non-software related projects.

**Comment by rrrutledge** [comment]
You're right!  The [old website](https://innersourcecommons.net/) had this - I hadn't realized it got lost in the transition.  Thanks, Vicky!

![image](https://github.com/InnerSourceCommons/innersourcecommons.org/assets/9609562/8bb33d05-7290-44b0-9154-067ed60dd35e)

**Comment by rrrutledge** [comment]
@voborgus can you help @andrea-kyurchiev to get a new graphic for this section?

![image](https://github.com/InnerSourceCommons/innersourcecommons.org/assets/9609562/d218938e-f07c-404b-bf1d-c9dee706cc7c)

**Comment by rrrutledge** [comment]
Thanks for fixing this, @andrea-kyurchiev!  I see it right there on innersourcecommons.org.  And thanks for reporting, Vicki!


![Image](https://github.com/InnerSourceCommons/innersourcecommons.org/assets/9609562/5d1582ee-0200-4ace-98b5-ca79c92f9245)
