### ISSUE TITLE
Locate a list of members

### ISSUE THREAD

**Issue by voborgus** [InnerSourceCommons/innersourcecommons.org#69]
**Is your feature request related to a problem? Please describe.**
We have no place currently where we list all official InnerSource Commons Members. 

**Describe the solution you'd like**
List all members on the site. Probably can be listed [here](https://innersourcecommons.net/about/), they can replace the picture near the membership section.

**Comment by claredillon** [comment]
There will be a new batch of Members announced in the next month I believe - so it perhaps makes sense for them to have a page - as the list will  be growing longer each year.

**Comment by voborgus** [comment]
Live on the site thanks to @spier

**Comment by spier** [comment]
Also adding a reference to the implemented "feature":
https://innersourcecommons.org/about/members/
