### ISSUE TITLE
Change company name for Thomas Boni on summit pages

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/innersourcecommons.org#867]
Hi there @andrea-kyurchiev 

1. Can you change Thomas Boni's company from Sopra Steria to R2Devops in the agenda table please?

2. Can you change Thomas Boni's company from R2Devops.io to R2Devops on his speaker bio as well please?

![image](https://github.com/user-attachments/assets/dfcacc5b-da62-49a2-8249-3abae8e3bef8)

![image](https://github.com/user-attachments/assets/d3d6e387-9d7f-4d95-9184-803add311a43)

**Comment by CiaraFlanagan** [comment]
@andrea-kyurchiev 

1st issue fixed but please can you fix typo in Speaker bio

**Comment by andrea-kyurchiev** [comment]
@CiaraFlanagan assuming this was fixed with #868
