### ISSUE TITLE
Twitter feed no longer showing on home page

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/innersourcecommons.org#895]
**Describe the bug**
Our X feed is no longer showing on our home page.  See image below.

**Expected behavior**
The feed should show every updated post.

**Additional context**
We've had some problems with our twitter account today. It appears to be fixed but the link to the live feed on our website has now disappeared.

![Image](https://github.com/user-attachments/assets/83d6ef3c-89a7-4a3d-82eb-9696334a9a63)

**Comment by andrea-kyurchiev** [comment]
@CiaraFlanagan it seems that its due to the account not being public and requiring authentication to view tweets. Try this to see if it fixes it https://9meters.com/entertainment/social-media/making-your-x-twitter-account-public

**Comment by CiaraFlanagan** [comment]
Hi @andrea-kyurchiev 

The @InnerSourceOrg account is definitely public and we've had that feed on our website for quite some time ...

Can you have another look at this please?

**Comment by andrea-kyurchiev** [comment]
@CiaraFlanagan it seems that that isn't the case. Do test it out for yourself by opening for example: https://x.com/public which doesnt require loging in to see tweets whereas https://x.com/InnerSourceOrg does. (Make sure to open them in an incognito window)

**Comment by CiaraFlanagan** [comment]
Ok - thanks @andrea-kyurchiev. I'll look into seeing what we can do here.

It's strange that this wasn't a problem before.

**Comment by andrea-kyurchiev** [comment]
@CiaraFlanagan not sure if this has changed but when Twitter changed to X they had rendered the embeds useless as you needed login to be able to show anything. Unsure if they have resolved that

**Comment by andrea-kyurchiev** [comment]
@CiaraFlanagan you can test once you've made changes on https://publish.twitter.com/ by entering the @InnerSourceOrg handle and  comparing how it shows up vs the @public(the one I used in the example) handle

**Comment by CiaraFlanagan** [comment]
Hi @andrea-kyurchiev 

So, I've double checked all our settings and read up some more and our account should be public.  

https://www.tweeteraser.com/resources/how-to-make-twitter-account-public-staying-visible-on-x/

![Image](https://github.com/user-attachments/assets/f9686d2d-f978-457d-949f-e378553aba2e)

**Comment by CiaraFlanagan** [comment]
However, there does appear to be some developments @andrea-kyurchiev 

I went onto: https://publish.twitter.com/, entered in @InnerSourceOrg and then got the code for embedding our X account back on the website: https://publish.twitter.com/?buttonType=FollowButton&query=%40InnerSourceOrg&widget=Button

Can you follow up on and get it up and running again ...

**Comment by andrea-kyurchiev** [comment]
@CiaraFlanagan the embedded timeline on the publish page still shows: ![Image](https://github.com/user-attachments/assets/00d0afe7-25ee-476d-9631-5a2101459674)

But we could opt for a follow embed: 
![Image](https://github.com/user-attachments/assets/07f09bc7-cda8-429e-b07f-9183e88768d4)

PS. It seems all the accounts that are "public" where the embed works are paying/verified accounts. Otherwise it requires a login and the embed doesnt work unless the user is logged into x

**Comment by CiaraFlanagan** [comment]
Hi @andrea-kyurchiev 

Thanks so much for all your work on this ... If we go for the other option, that would be great.
