### ISSUE TITLE
Review how we format the Pattern Search Workshop on the summit event page

### ISSUE THREAD

**Issue by CiaraFlanagan** [InnerSourceCommons/innersourcecommons.org#896]
Hi @andrea-kyurchiev 

We have a kind of tricky formatting issue on the [Summit page](https://innersourcecommons.org/events/isc-2024/). 

There's one workshop happening on a third track on the second day of the summit and it spans a break and two talks. 

@OliveCannon did a great job adding it but is there a way to re-format this tricky slot so that we can clearly see when it's scheduled alongside Track 1 and Track 2 without having the table cells above and beneath it looking half finished/blank - I'm wondering if it's even an option to 'grey out' all that redundant space.  

Would that be possible?

![Image](https://github.com/user-attachments/assets/3d5bc55d-81da-4108-b22a-31719d86b62e)

![Image](https://github.com/user-attachments/assets/559b20c6-29a2-4277-a0a3-f86535078cde)

**Comment by andrea-kyurchiev** [comment]
@CiaraFlanagan as far as graying it out, that wont be possible for the moment spare for making the whole table grayed out. We could get rid of the border to make it look like this ![Image](https://github.com/user-attachments/assets/8e56ce5e-436d-4949-90a5-099fbfeacc24)

**Comment by CiaraFlanagan** [comment]
Hi @andrea-kyurchiev 

Thanks for that feedback.  Let's forget about 'greying out' and let's try and **keep the border** . 

Can you show me what it will like with the third track for Isabel's workshop?

**Comment by CiaraFlanagan** [comment]
Is there a way to make the Patterns Workshop slot look 'clearer' and 'neater' on the agenda table @andrea-kyurchiev?
